name: Build

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Get dependencies
        run: sudo apt update && sudo apt install -y libxi-dev libxcursor-dev libxinerama-dev libudev-dev libopenal-dev libvorbis-dev libflac-dev libxrandr-dev libfreetype6-dev make libgl1-mesa-dev
        if: matrix.os == 'ubuntu-latest'

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Upload artifacts
          uses: 'actions/upload-artifact@v2'
          with:
              name: FastestPizzaDelivery ${{ matrix.os }}
              path: |
                ${{ github.workspace }}/build/bin/FastestPizzaDelivery
                ${{ github.workspace }}/build/bin/Release/FastestPizzaDelivery.exe
              retention-days: 2
